name: go mod tidy

on:
  pull_request:

jobs:
  gomodtidy:
    name: tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: go mod tidy
        run: go mod tidy
      - name: git diff
        run: |
          git diff --exit-code --quiet
          if [ $? -ne 0 ]; then
            echo "Please run 'go mod tidy' and commit the changes"
            exit 1
          fi
