name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gotest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: go test
        run: go test -v -race -cover ./...
